### ISSUE TITLE
Range 207.46.13.0 - 207.46.13.255 false positive

### ISSUE THREAD

**Issue by Ythan** [client9/ipcat#136]
Hi, you have 207.46.13.0/24 flagged as Microsoft Azure IPs belonging to http://www.windowsazure.com/en-us/, however it's been reported to me that this is a false positive and these IPs are used by Bing search engine spiders. Unlike typical Azure IPs, these IPs resolve to search.msn.com.

Edit: also 157.55.39.0/24 and 40.77.167.0/24

**Comment by shawnps** [comment]
Hi @Ythan thanks for the ticket.

The Azure IPs are all taken directly from Microsoft's public list of Azure datacenter ranges:

https://www.microsoft.com/en-us/download/confirmation.aspx?id=41653

Since the purpose of this library is to tag IPs that are coming from datacenters rather than from end users, this seems correct to me.

If you're looking to verify Bingbot I would take a look at Bing's docs on that: https://www.bing.com/webmaster/help/how-to-verify-bingbot-3905dc26
